# Puedes borrar "version:", es obsoleta.

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  selenium:
    image: selenium/standalone-chromium:125.0
    shm_size: 2g
    environment:
      - SE_ENABLE_UI=true
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - ./selenium-profiles:/home/seluser/profiles
    entrypoint: ["/bin/bash","-lc","mkdir -p /home/seluser/profiles/aliexpress && chown -R seluser:seluser /home/seluser/profiles ; exec /opt/bin/entry_point.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:4444/status | grep -q '\"ready\": *true'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info --concurrency=1
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      SELENIUM_REMOTE_URL: http://selenium:4444
      SELENIUM_PROFILE_DIR: /home/seluser/profiles/aliexpress
      OUTPUT_DIR: /app/data         # debe coincidir con tasks.py
      VISUAL_MODE: "1"
    volumes:
      - ./data:/app/data            # CSVs visibles desde el host
    user: "0"                       # en Windows evita problemas de permisos
    depends_on:
      selenium:
        condition: service_healthy
      redis:
        condition: service_started

  web:
    build: .
    command: python app.py
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "5000:5000"
    depends_on:
      - redis
